<?php
/**
  * Generated by ClassGenerator
  * Antoine Plagnol
  * More info : https://github.com/plagnol
  * Date : 31/05/2018 00:00:00
  */
 
class Pourcombien
{
 
    private $id;
 
    private $question;
 
    private $pourcombien;
 
    private $valeur1;
 
    private $valeur2;
 
    /**
    *@return string
    */
    
     public function getId()
     {
          return $this->id;
     }
 
    /**
    *@return string
    */
    
     public function getQuestion()
     {
          return $this->question;
     }
 
    /**
    *@return int
    */
    
     public function getPourcombien()
     {
          return $this->pourcombien;
     }
 
    /**
    *@return int
    */
    
     public function getValeur1()
     {
          return $this->valeur1;
     }
 
    /**
    *@return int
    */
    
     public function getValeur2()
     {
          return $this->valeur2;
     }
 
     /**
     * Set uniqId
     */
     
      public function setId()
      {
           $this->id = $this->generateRandomString(25);
      }
 
     /**
     *@param string $question
     */
     
      public function setQuestion( $question )
      {
           $this->question = $question;
      }
 
     /**
     *@param int $pourcombien
     */
     
      public function setPourcombien( $pourcombien )
      {
           $this->pourcombien = $pourcombien;
      }
 
     /**
     *@param int $valeur1
     */
     
      public function setValeur1( $valeur1 )
      {
           $this->valeur1 = $valeur1;
      }
 
     /**
     *@param int $valeur2
     */
     
      public function setValeur2( $valeur2 )
      {
           $this->valeur2 = $valeur2;
      }

    /**
     *
     * @param int $lenght
     * @return string Random string $lenght-long
     */
    function generateRandomString($lenght)
    {
        $characters = '0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ';
        $charactersLength = strlen($characters);
        $randomString = '';
        for ($i = 0; $i < $lenght; $i ++) {
            $randomString .= $characters[rand(0, $charactersLength - 1)];
        }
        return $randomString;
    }
}
